### ISSUE TITLE
Cannot compile the package

### ISSUE THREAD

**Issue by zfxw0206** [JenniferBuehler/convenience-pkgs#2]
I download the "convenience-pkgs" in my catkin space and try to compile it. But I got the following error:

[ 43%] CMakeFiles/mesh_converter.dir/src/converter.cpp.o: In function `convert(std::string const&, std::string const&, std::string const&)':
converter.cpp:(.text+0x48c): undefined reference to`Assimp::Importer::Importer()'
converter.cpp:(.text+0x49f): undefined reference to `Assimp::Importer::ReadFile(char const*, unsigned int)'
converter.cpp:(.text+0x4b5): undefined reference to`Assimp::Exporter::Exporter()'
converter.cpp:(.text+0x4cd): undefined reference to `Assimp::Exporter::Export(aiScene const*, char const*, char const*, unsigned int)'
converter.cpp:(.text+0x50d): undefined reference to`Assimp::Exporter::~Exporter()'
converter.cpp:(.text+0x517): undefined reference to `Assimp::Importer::~Importer()'
converter.cpp:(.text+0x74c): undefined reference to`Assimp::Importer::~Importer()'
converter.cpp:(.text+0x76c): undefined reference to `Assimp::Exporter::~Exporter()'
collect2: error: ld returned 1 exit status
make[2]: **\* [/home/administrator/wspace/devel/lib/assimp_mesh_converter/mesh_converter] Error 1
make[1]: **\* [convenience-pkgs/assimp_mesh_converter/CMakeFiles/mesh_converter.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....

Did I do something wrong or miss some steps?
Thank you!

**Comment by JenniferBuehler** [comment]
Hi, 

This is because a new dependency of the new package assimp_mesh_converter. Installation instructions will be updated shortly.
Meanwhile, you can either install assimp (ubuntu package assimp-dev) or remove  the folder assimp_mesh_converter from the cloned repo.

Cheers
Jennifer

**Comment by JenniferBuehler** [comment]
Oh, just saw it is a linker error. I'll check on this again when I get to my laptop.

**Comment by JenniferBuehler** [comment]
Hey,

I'm guessing it is a search path missing in the Findassimp.cmake, because you must have the assimp-dev package (otherwise the compiler would complain before the linker)... essentially, the path to the library is probably not in the cmake variable ASSIMP_LIBRARIES on your system.

Can you please post the output of `locate libassimp.so`? Which Linux OS are you using, e.g. which ubuntu version?

If you don't need the assimp_mesh_converter, just delete the directory. I'll probably move it somewhere else some time soon anyway, it's new and I have just put it in convenience-pkgs for now. Anyway, it would still help me fix the issue if you let me know which system you are using, thanks!

Jennifer

**Comment by zfxw0206** [comment]
I am using Ubuntu 14.04 and here is the output of locate libassimp.so:
/usr/lib/libassimp.so
/usr/lib/libassimp.so.3
/usr/lib/libassimp.so.3.0.1264

**Comment by JenniferBuehler** [comment]
Ok, that's odd. I have the same system configuration so I've done a complete fresh re-build to see if I can reproduce it, and then got the same issue. Compiling a second time then fixed it. But that's not how it should be, so I fixed the problem in the cmake files.

The problem was that on the first compiler run, ASSIMP_LIBRARIES was not set, only ASSIMP_LIBRARY. Then on the second compile run, both variables were set. Another one of my packages must cache the cmake variable, not sure how the whole process works, but that's the only explanation I have at this point ;)

I've added both variables to the link target and now it compiles on the first run as well.
Can you try again and let me know if it works for you as well now?

Cheers
Jennifer

**Comment by JenniferBuehler** [comment]
Assuming this has been fixed, please re-open if not.
